### ISSUE TITLE
Attach to Server 

### ISSUE THREAD

**Issue by gedoensmax** [jusito/docker-ftb-alpine#1]
Is there any way to connect to the server prompt and execute commands ? a simple `docker attach` does not seem to work. 
If i `exec` myself into the container if also does not work. 

The reason for this is actually that i can no longer start my mc server because  of this: 
```
[21:25:24] [Server thread/INFO] [FML]: Registry VillagerProfession: Found a missing id from the world stevescarts:santa
[21:25:24] [Server thread/ERROR] [FML]: Unidentified mapping from registry minecraft:villagerprofessions
[21:25:24] [Server thread/ERROR] [FML]:     stevescarts:santa: 10
[21:25:24] [Server thread/WARN] [FML]: Forge Mod Loader detected missing registry entries.

There are 1 missing entries in this save.
If you continue the missing entries will get removed.
A world backup will be automatically created in your saves directory.

Missing minecraft:villagerprofessions:
    stevescarts:santa


Run the command /fml confirm or or /fml cancel to proceed.
Alternatively start the server with -Dfml.queryResult=confirm or -Dfml.queryResult=cancel to preselect the answer.

```

**Comment by jusito** [comment]
I must admit I hadn't thought of that.
The commands are needed as Java Parameter, so you can use the environment variables.

You can try:
1. Stop your container
2. Run a new container, just for the upgrade process, with `-e JAVA_PARAMETERS="-Dfml.queryResult=confirm"`
```docker run --rm -v MyVolume:/home/docker:rw -e JAVA_PARAMETERS="-Dfml.queryResult=confirm" jusito/docker-ftb-alpine:YourVersion (if you using base directly, you need to insert downloadlink and md5```
3. stop new container, restart your old container

Iam unsure if you can confirm it from inside of the container, if you know how to:
`docker exec -it YourContainer /bin/sh` and you are on the shell

Edit:
Is rcon already working in this stage? (cant test this case)

**Comment by jusito** [comment]
Same situation for me, tried above, server booted up in step 2, created a world backup aso and reported [done]. But in step 3, still need to confirm it? Weird, but now I have a working example.

**Comment by jusito** [comment]
Ok worked for me:
1. Stop your container
2. Run new container, used:
```
docker run -it --rm --name "RLCraft-MS3-update" \
 -p 25568:25565/tcp \
 -e JAVA_PARAMETERS="-Xms4G -Xmx4G -Dfml.queryResult=confirm" \
 -v "RLCraft-MS3:/home/docker:rw" \
 "jusito/docker-ftb-alpine:RLCraft-2.8.1-1.12.2"
```
3. connect to the server and play a few minutes (maybe not needed but repeated this 3 times and needed around 30-120 seconds, still weird)
4. disconnect, stop new container, restart old container, done

**Comment by jusito** [comment]
Because of the issue, I have come across another problem related to this.
In step 3 I assumed, that forge handles SIGTERM but it doesnt, the server doesn't exit the clean way and therefore need some time to run. 
https://github.com/MinecraftForge/MinecraftForge/issues/2998
https://github.com/MinecraftForge/MinecraftForge/issues/3027

The only clean method is to send "stop". The fastest solution would be to use stg like tmux but I want to avoid additional dependencies. I have successfully tested named pipes as a solution, this should make step 3 obsolete.

I will introduce in next version something like `docker exec CONTAINER query '/fml confirm'` but this isn't limited to this command.
And the server will shutdown with sending "stop".
